# Example configuration for using HC-12 with ESPHome
esphome:
  name: hc12-component

esp8266:
  board: nodemcuv2
  restore_from_flash: true

external_components:
  - source: github://madurapa/esphome-hc12@main

logger:
  level: INFO

uart:
  id: uart_12
  tx_pin: GPIO12
  rx_pin: GPIO14
  baud_rate: 9600
  rx_buffer_size: 256

hc12:
  id: hc12_component
  uart_id: uart_12

text_sensor:
  - platform: hc12
    name: "HC-12 Received Data"
    id: hc12_received_data
    uart_id: uart_12
